# -*- encoding: utf-8 -*-
{
    'name': 'T4 Clinical Task types',
    'version': '0.1',
    'category': 'Clinical',
    'license': 'AGPL-3',
    'summary': '',
    'description': """    """,
    'author': 'Tactix4',
    'website': 'http://www.tactix4.com/',
    'depends': ['t4clinical_base','project','hr'],
    'data': [
             'window_actions.xml',
             'patient_placement_view.xml',
             'placement_wizard_view.xml',
             'types.xml', 
             'menuitem.xml',
             'ir.model.access.csv'],
    'demo': [],
    'css': [],
    'js': [],
    'qweb': [],
    'images': [],
    'application': True,
    'installable': True,
    'active': False,
}