from . import test_eobs_settings
from . import test_eobs_settings_manually_set
from . import test_spell_obs_stop_property
from . import test_nh_clinical_wardboard_escalation_tasks
from . import test_nh_clinical_wardboard_toggle_obs_stop
from . import test_nh_clinical_wardboard_toggle_obs_stop_flag
from . import test_nh_eobs_api_get_active_observations
