from . import test_eobs_settings
from . import test_eobs_settings_manually_set
from . import test_spell_obs_stop_property
from . import test_nh_clinical_wardboard_escalation_tasks
from . import test_nh_clinical_wardboard_toggle_obs_stop
from . import test_nh_clinical_wardboard_toggle_obs_stop_flag
from . import test_nh_eobs_api_get_active_observations
from . import test_nh_eobs_api_transfer
# from . import test_nh_clinical_wardboard_prompt_user_for_obs_stop_reason
from . import test_nh_clinical_wardboard_cancels_ews_tasks
from . import test_nh_eobs_mobile_process_patient_list
from . import test_nh_clinical_wardboard_read_obs_stop
from . import test_nh_clinical_wardboard_restarts_ews_tasks
