# -*- encoding: utf-8 -*-
{
    'name': 'T4 Clinical API',
    'version': '0.1',
    'category': 'Clinical',
    'license': 'AGPL-3',
    'summary': '',
    'description': """    """,
    'author': 'Tactix4',
    'website': 'http://tactix4.net/',
    'depends': ['t4clinical_base','t4clinical_activity_types','hr'],
    'data': [],
    'demo': [],
    'css': [],
    'js': [],
    'qweb': [],
    'images': [],
    'application': True,
    'installable': True,
    'active': False,
}