# -*- encoding: utf-8 -*-
{
    'name': 'LiveObs Demo Loader',
    'version': '0.1',
    'category': 'Clinical',
    'license': 'AGPL-3',
    'summary': 'Creates a demo installation of LiveObs.',
    'description': """
    Creates demo hospitals, wards, staff, patients, and more to produce a \
    usable installation of LiveObs that can be used for demoing its \
    functionality.
    """,
    'author': 'Neova Health',
    'website': 'http://www.neovahealth.co.uk/',
    'depends': ['nh_eobs'],
    'data': [
        'data/pos.xml',
        'data/ward_a/demo_locations.xml',
        'data/ward_b/demo_locations.xml',
        'data/ward_c/demo_locations.xml',
        'data/ward_d/demo_locations.xml',
        'data/ward_e/demo_locations.xml',
        'data/users.xml',
        'data/ward_a/demo_users.xml',
        'data/ward_b/demo_users.xml',
        'data/ward_c/demo_users.xml',
        'data/ward_d/demo_users.xml',
        'data/ward_e/demo_users.xml',
        'data/ward_a/demo_patients.xml',
        'data/ward_b/demo_patients.xml',
        'data/ward_c/demo_patients.xml',
        'data/ward_d/demo_patients.xml',
        'data/ward_e/demo_patients.xml',
        'data/ward_a/demo_spells.xml',
        'data/ward_b/demo_spells.xml',
        'data/ward_c/demo_spells.xml',
        'data/ward_d/demo_spells.xml',
        'data/ward_e/demo_spells.xml',
        'data/ward_a/demo_admissions.xml',
        'data/ward_b/demo_admissions.xml',
        'data/ward_c/demo_admissions.xml',
        'data/ward_d/demo_admissions.xml',
        'data/ward_e/demo_admissions.xml',
        'data/ward_a/demo_placements.xml',
        'data/ward_b/demo_placements.xml',
        'data/ward_c/demo_placements.xml',
        'data/ward_d/demo_placements.xml',
        'data/ward_e/demo_placements.xml',
        'data/ward_a/demo_news.xml',
        'data/ward_b/demo_news.xml',
        'data/ward_c/demo_news.xml',
        'data/ward_d/demo_news.xml',
        'data/ward_e/demo_news.xml',
        'data/ward_a/demo_shifts.xml',
        'data/ward_b/demo_shifts.xml',
        'data/ward_c/demo_shifts.xml',
        'data/ward_d/demo_shifts.xml',
        'data/ward_e/demo_shifts.xml'
    ],
    'application': True,
    'installable': True,
    'active': False,
}
