# -*- encoding: utf-8 -*-
{
    'name': 'T4 Clinical Internal Demo',
    'version': '0.1',
    'category': 'Clinical',
    'license': 'AGPL-3',
    'summary': '',
    'description': """    """,
    'author': 'Tactix4',
    'website': 'http://www.tactix4.com/',
    'depends': ['t4clinical_base','t4clinical_task_types'],
    'data': ['master_data.xml',
             'wardboard_view.xml',
             #'wizard/patient_adt_wizard_view.xml',
             #'wizard/assign_bed_and_obs_frequency_wizard_view.xml',
             'ir.model.access.csv'],
    'application': True,
    'installable': True,
    'active': False,
}