# Part of NHClinical. See LICENSE file for full copyright and licensing details
# -*- coding: utf-8 -*-
{
    'name': 'NH Demo Data Set',
    'version': '0.1',
    'category': 'Clinical',
    'license': 'AGPL-3',
    'summary': 'Demo Data Set for Open eObs',
    'description': """     """,
    'author': 'Neova Health',
    'website': 'http://www.neovahealth.co.uk/',
    'depends': ['nh_eobs'],
    'data': ['data/pos.xml',
             'data/ward_a/demo_locations.xml',
             'data/ward_b/demo_locations.xml',
             'data/ward_c/demo_locations.xml',
             'data/ward_d/demo_locations.xml',
             'data/ward_e/demo_locations.xml',
             'data/users.xml',
             'data/ward_a/demo_users.xml',
             'data/ward_b/demo_users.xml',
             'data/ward_c/demo_users.xml',
             'data/ward_d/demo_users.xml',
             'data/ward_e/demo_users.xml',
             'data/ward_a/demo_patients.xml',
             'data/ward_b/demo_patients.xml',
             'data/ward_c/demo_patients.xml',
             'data/ward_d/demo_patients.xml',
             'data/ward_e/demo_patients.xml',
             'data/ward_a/demo_spells.xml',
             'data/ward_b/demo_spells.xml',
             'data/ward_c/demo_spells.xml',
             'data/ward_d/demo_spells.xml',
             'data/ward_e/demo_spells.xml',
             'data/ward_a/demo_admissions.xml',
             'data/ward_b/demo_admissions.xml',
             'data/ward_c/demo_admissions.xml',
             'data/ward_d/demo_admissions.xml',
             'data/ward_e/demo_admissions.xml',
             'data/ward_a/demo_placements.xml',
             'data/ward_b/demo_placements.xml',
             'data/ward_c/demo_placements.xml',
             'data/ward_d/demo_placements.xml',
             'data/ward_e/demo_placements.xml',
             'data/ward_a/demo_news.xml',
             'data/ward_b/demo_news.xml',
             'data/ward_c/demo_news.xml',
             'data/ward_d/demo_news.xml',
             'data/ward_e/demo_news.xml'],
    'demo': [],
    'css': [],
    'js': [],
    'qweb': [],
    'images': [],
    'application': True,
    'installable': True,
    'active': False,
}
