# -*- encoding: utf-8 -*-
{
    'name': 'T4 Clinical Improved',
    'version': '0.1',
    'category': 'Clinical',
    'license': 'AGPL-3',
    'summary': '',
    'description': """    """,
    'author': 'Tactix4',
    'website': 'http://www.tactix4.com/',
    'depends': ['project','hr'],
    'data': ['data.xml', 
             'pos_view.xml',
             'task_view.xml',
             'location_view.xml',
             'patient_view.xml',
             'task_data_type_view.xml',
             'employee_view.xml',
             'user_view.xml'],
    'demo': [],
    'css': [],
    'js': [],
    'qweb': [],
    'images': [],
    'application': True,
    'installable': True,
    'active': False,
}