# -*- encoding: utf-8 -*-
{
    'name': 'T4 Clinical Improved',
    'version': '0.1',
    'category': 'Clinical',
    'license': 'AGPL-3',
    'summary': '',
    'description': """    """,
    'author': 'Tactix4',
    'website': 'http://www.tactix4.com/',
    'depends': ['project','hr'],
    'data': ['task_view.xml','base_data.xml','task_data.xml'],
    'demo': ['demo_data.xml',],
    'css': [],
    'js': [],
    'qweb': [],
    'images': [],
    'application': True,
    'installable': True,
    'active': False,
}