import test_mobile_controller_routes
import test_mobile_controller_methods

# NFC tests
# import test_nfc_model

# Controller HTML rendering tests
import test_HTML_login
import test_HTML_patient_detail
import test_HTML_patient_list
import test_HTML_stand_in_list
import test_HTML_task_detail
import test_HTML_task_list
