# -*- encoding: utf-8 -*-
{
    'name': 'NH Clinical UI',
    'version': '0.1',
    'category': 'Clinical',
    'license': 'AGPL-3',
    'summary': '',
    'description': """    """,
    'author': 'Tactix4',
    'website': 'http://www.tactix4.com/',
    'depends': ['nh_clinical_base','nh_clinical_activity_types', 'nh_clinical_api', 'nhc_d3'],
    'data': ['wizard/responsibility_allocation_wizard.xml',
             'wizard/cancel_notifications_view.xml',
             'views/wardboard_view.xml',
             'views/workload_view.xml',
             'views/placement_view.xml',
             'views/userboard_view.xml',
             'views/overdue_view.xml',
             'views/views.xml',
             'views/menuitem.xml',
             'views/report_template.xml',
             'security/ir.model.access.csv'],
    'qweb': ['static/src/xml/nh_clinical_ui.xml'],
    'application': True,
    'installable': True,
    'active': False,
}