from .models import nh_clinical_spell
from .models import nh_clinical_settings
from .models import nh_clinical_wardboard
from .models import nh_eobs_api
from .wizard import nh_clinical_patient_monitoring_exception_select_reason
from .models import nh_eobs_mobile_main
from .models import nh_clinical_sql
from .models import nh_eobs_ward_dashboard
from .models import nh_clinical_patient_observation_ews
from .models import nh_clinical_notification_clinical_review
from .models import nh_clinical_doctor_activities
from .models import nh_clinical_overdue
