/**
 * Created by colinwren on 22/06/15.
 */
var ews_data = {
        empty: [],
        single_record: [{
                __last_update: "2014-12-01 16:16:53",
                activity_id: [700, "NEWS Observation"],
                avpu_text: "A",
                blood_pressure_diastolic: 80,
                blood_pressure_systolic: 120,
                body_temperature: 40,
                clinical_risk: "Medium",
                concentration: false,
                cpap_peep: false,
                create_date: "2014-12-01 13:15:13",
                create_uid: [1, "Administrator"],
                date_started: "2014-12-01 16:16:42",
                date_terminated: "2014-12-01 16:16:53",
                device_id: false,
                display_name: "False",
                flow_rate: false,
                frequency: 240,
                id: 83,
                indirect_oxymetry_spo2: 90,
                is_partial: false,
                mews_score: 0,
                name: false,
                niv_backup: false,
                niv_epap: false,
                niv_ipap: false,
                none_values: "[]",
                null_values: "['niv_epap', 'concentration', 'flow_rate', 'cpap_peep', 'niv_ipap', 'niv_backup']",
                order_by: false,
                oxygen_administration_flag: false,
                partial_reason: false,
                patient_id: [11, "Littel, Alfreda"],
                pulse_rate: 80,
                respiration_rate: 18,
                score: 5,
                state: "completed",
                terminate_uid: [19, "Nadine Bullock"],
                three_in_one: true,
                write_date: "2014-12-01 16:16:53",
                write_uid: [1, "Administrator"]
        }],
        incomplete_record: [{
                __last_update: "2014-12-01 16:16:53",
                activity_id: [700, "NEWS Observation"],
                avpu_text: "A",
                blood_pressure_diastolic: 80,
                blood_pressure_systolic: 120,
                body_temperature: 40,
                clinical_risk: "Medium",
                concentration: false,
                cpap_peep: false,
                create_date: "2014-12-01 13:15:13",
                create_uid: [1, "Administrator"],
                date_started: "2014-12-01 16:16:42",
                date_terminated: "2014-12-01 16:16:53",
                device_id: false,
                display_name: "False",
                flow_rate: false,
                frequency: 240,
                id: 83,
                indirect_oxymetry_spo2: 90,
                is_partial: true,
                mews_score: 0,
                name: false,
                niv_backup: false,
                niv_epap: false,
                niv_ipap: false,
                none_values: "['respiration_rate']",
                null_values: "['niv_epap', 'concentration', 'flow_rate', 'cpap_peep', 'niv_ipap', 'niv_backup']",
                order_by: false,
                oxygen_administration_flag: false,
                partial_reason: false,
                patient_id: [11, "Littel, Alfreda"],
                pulse_rate: 80,
                respiration_rate: false,
                score: false,
                state: "completed",
                terminate_uid: [19, "Nadine Bullock"],
                three_in_one: true,
                write_date: "2014-12-01 16:16:53",
                write_uid: [1, "Administrator"]
        }],
        multiple_records: [
                {
                        __last_update: "2014-12-01 16:16:53",
                        activity_id: [700, "NEWS Observation"],
                        avpu_text: "A",
                        blood_pressure_diastolic: 80,
                        blood_pressure_systolic: 120,
                        body_temperature: 40,
                        clinical_risk: "Medium",
                        concentration: false,
                        cpap_peep: false,
                        create_date: "2014-12-01 13:15:13",
                        create_uid: [1, "Administrator"],
                        date_started: "2014-12-01 16:16:42",
                        date_terminated: "2014-12-01 16:16:53",
                        device_id: false,
                        display_name: "False",
                        flow_rate: false,
                        frequency: 240,
                        id: 83,
                        indirect_oxymetry_spo2: 90,
                        is_partial: false,
                        mews_score: 0,
                        name: false,
                        niv_backup: false,
                        niv_epap: false,
                        niv_ipap: false,
                        none_values: "[]",
                        null_values: "['niv_epap', 'concentration', 'flow_rate', 'cpap_peep', 'niv_ipap', 'niv_backup']",
                        order_by: false,
                        oxygen_administration_flag: false,
                        partial_reason: false,
                        patient_id: [11, "Littel, Alfreda"],
                        pulse_rate: 80,
                        respiration_rate: 18,
                        score: 5,
                        state: "completed",
                        terminate_uid: [19, "Nadine Bullock"],
                        three_in_one: true,
                        write_date: "2014-12-01 16:16:53",
                        write_uid: [1, "Administrator"]
                },
                {
                        __last_update: "2014-12-01 17:16:53",
                        activity_id: [700, "NEWS Observation"],
                        avpu_text: "A",
                        blood_pressure_diastolic: 80,
                        blood_pressure_systolic: 120,
                        body_temperature: 40,
                        clinical_risk: "Medium",
                        concentration: false,
                        cpap_peep: false,
                        create_date: "2014-12-01 14:15:13",
                        create_uid: [1, "Administrator"],
                        date_started: "2014-12-01 17:16:42",
                        date_terminated: "2014-12-01 17:16:53",
                        device_id: false,
                        display_name: "False",
                        flow_rate: false,
                        frequency: 240,
                        id: 83,
                        indirect_oxymetry_spo2: 90,
                        is_partial: false,
                        mews_score: 0,
                        name: false,
                        niv_backup: false,
                        niv_epap: false,
                        niv_ipap: false,
                        none_values: "[]",
                        null_values: "['niv_epap', 'concentration', 'flow_rate', 'cpap_peep', 'niv_ipap', 'niv_backup']",
                        order_by: false,
                        oxygen_administration_flag: false,
                        partial_reason: false,
                        patient_id: [11, "Littel, Alfreda"],
                        pulse_rate: 80,
                        respiration_rate: 18,
                        score: 5,
                        state: "completed",
                        terminate_uid: [19, "Nadine Bullock"],
                        three_in_one: true,
                        write_date: "2014-12-01 17:16:53",
                        write_uid: [1, "Administrator"]
                }
        ],
        multi_partial: [
                {
                        __last_update: "2014-12-01 16:16:53",
                        activity_id: [700, "NEWS Observation"],
                        avpu_text: "A",
                        blood_pressure_diastolic: 80,
                        blood_pressure_systolic: 120,
                        body_temperature: 40,
                        clinical_risk: "Medium",
                        concentration: '100%',
                        cpap_peep: false,
                        create_date: "2014-12-01 13:15:13",
                        create_uid: [1, "Administrator"],
                        date_started: "2014-12-01 16:16:42",
                        date_terminated: "2014-12-01 16:16:53",
                        device_id: 12,
                        display_name: "False",
                        flow_rate: '15lpm',
                        frequency: 240,
                        id: 83,
                        indirect_oxymetry_spo2: 90,
                        is_partial: false,
                        mews_score: 0,
                        name: false,
                        niv_backup: false,
                        niv_epap: false,
                        niv_ipap: false,
                        none_values: "[]",
                        null_values: "['niv_epap','cpap_peep', 'niv_ipap', 'niv_backup']",
                        order_by: false,
                        oxygen_administration_flag: true,
                        partial_reason: false,
                        patient_id: [11, "Littel, Alfreda"],
                        pulse_rate: 80,
                        respiration_rate: 18,
                        score: 5,
                        state: "completed",
                        terminate_uid: [19, "Nadine Bullock"],
                        three_in_one: true,
                        write_date: "2014-12-01 16:16:53",
                        write_uid: [1, "Administrator"],

                },
                {
                        __last_update: "2014-12-01 17:16:53",
                        activity_id: [700, "NEWS Observation"],
                        avpu_text: "A",
                        blood_pressure_diastolic: 80,
                        blood_pressure_systolic: 120,
                        body_temperature: 40,
                        clinical_risk: "Medium",
                        concentration: false,
                        cpap_peep: false,
                        create_date: "2014-12-01 14:15:13",
                        create_uid: [1, "Administrator"],
                        date_started: "2014-12-01 17:16:42",
                        date_terminated: "2014-12-01 17:16:53",
                        device_id: false,
                        display_name: "False",
                        flow_rate: false,
                        frequency: 240,
                        id: 83,
                        indirect_oxymetry_spo2: 90,
                        is_partial: false,
                        mews_score: 0,
                        name: false,
                        niv_backup: false,
                        niv_epap: false,
                        niv_ipap: false,
                        none_values: "['respiration_rate']",
                        null_values: "['niv_epap', 'concentration', 'flow_rate', 'cpap_peep', 'niv_ipap', 'niv_backup']",
                        order_by: false,
                        oxygen_administration_flag: false,
                        partial_reason: false,
                        patient_id: [11, "Littel, Alfreda"],
                        pulse_rate: 80,
                        respiration_rate: 28,
                        score: 5,
                        state: "completed",
                        terminate_uid: [19, "Nadine Bullock"],
                        three_in_one: true,
                        write_date: "2014-12-01 17:16:53",
                        write_uid: [1, "Administrator"]
                },
                {
                        __last_update: "2014-12-01 18:16:53",
                        activity_id: [700, "NEWS Observation"],
                        avpu_text: "A",
                        blood_pressure_diastolic: 80,
                        blood_pressure_systolic: 120,
                        body_temperature: 40,
                        clinical_risk: "Medium",
                        concentration: false,
                        cpap_peep: false,
                        create_date: "2014-12-01 15:15:13",
                        create_uid: [1, "Administrator"],
                        date_started: "2014-12-01 18:16:42",
                        date_terminated: "2014-12-01 18:16:53",
                        device_id: false,
                        display_name: "False",
                        flow_rate: false,
                        frequency: 240,
                        id: 83,
                        indirect_oxymetry_spo2: 90,
                        is_partial: false,
                        mews_score: 0,
                        name: false,
                        niv_backup: false,
                        niv_epap: false,
                        niv_ipap: false,
                        none_values: "[]",
                        null_values: "['niv_epap', 'concentration', 'flow_rate', 'cpap_peep', 'niv_ipap', 'niv_backup']",
                        order_by: false,
                        oxygen_administration_flag: false,
                        partial_reason: false,
                        patient_id: [11, "Littel, Alfreda"],
                        pulse_rate: 80,
                        respiration_rate: 18,
                        score: 5,
                        state: "completed",
                        terminate_uid: [19, "Nadine Bullock"],
                        three_in_one: true,
                        write_date: "2014-12-01 17:16:53",
                        write_uid: [1, "Administrator"]
                }
        ],
        multi_days: [
                {
                        __last_update: "2014-12-01 16:16:53",
                        activity_id: [700, "NEWS Observation"],
                        avpu_text: "A",
                        blood_pressure_diastolic: 80,
                        blood_pressure_systolic: 120,
                        body_temperature: 40,
                        clinical_risk: "Medium",
                        concentration: false,
                        cpap_peep: false,
                        create_date: "2014-11-30 13:15:13",
                        create_uid: [1, "Administrator"],
                        date_started: "2014-11-30 16:16:42",
                        date_terminated: "2014-11-30 16:16:53",
                        device_id: false,
                        display_name: "False",
                        flow_rate: false,
                        frequency: 240,
                        id: 83,
                        indirect_oxymetry_spo2: 90,
                        is_partial: false,
                        mews_score: 0,
                        name: false,
                        niv_backup: false,
                        niv_epap: false,
                        niv_ipap: false,
                        none_values: "[]",
                        null_values: "['niv_epap', 'concentration', 'flow_rate', 'cpap_peep', 'niv_ipap', 'niv_backup']",
                        order_by: false,
                        oxygen_administration_flag: false,
                        partial_reason: false,
                        patient_id: [11, "Littel, Alfreda"],
                        pulse_rate: 80,
                        respiration_rate: 18,
                        score: 5,
                        state: "completed",
                        terminate_uid: [19, "Nadine Bullock"],
                        three_in_one: true,
                        write_date: "2014-12-01 16:16:53",
                        write_uid: [1, "Administrator"]
                },
                {
                        __last_update: "2014-12-01 18:16:53",
                        activity_id: [700, "NEWS Observation"],
                        avpu_text: "A",
                        blood_pressure_diastolic: 80,
                        blood_pressure_systolic: 120,
                        body_temperature: 40,
                        clinical_risk: "Medium",
                        concentration: false,
                        cpap_peep: false,
                        create_date: "2014-12-01 15:15:13",
                        create_uid: [1, "Administrator"],
                        date_started: "2014-12-01 18:16:42",
                        date_terminated: "2014-12-01 18:16:53",
                        device_id: false,
                        display_name: "False",
                        flow_rate: false,
                        frequency: 240,
                        id: 83,
                        indirect_oxymetry_spo2: 90,
                        is_partial: false,
                        mews_score: 0,
                        name: false,
                        inspired_oxygen: '12lpm',
                        niv_backup: false,
                        niv_epap: false,
                        niv_ipap: false,
                        none_values: "[]",
                        null_values: "['niv_epap', 'concentration', 'flow_rate', 'cpap_peep', 'niv_ipap', 'niv_backup']",
                        order_by: false,
                        oxygen_administration_flag: false,
                        partial_reason: false,
                        patient_id: [11, "Littel, Alfreda"],
                        pulse_rate: 80,
                        respiration_rate: 18,
                        score: 5,
                        state: "completed",
                        terminate_uid: [19, "Nadine Bullock"],
                        three_in_one: true,
                        write_date: "2014-12-01 17:16:53",
                        write_uid: [1, "Administrator"]
                },
                {
                        __last_update: "2014-12-01 17:16:53",
                        activity_id: [700, "NEWS Observation"],
                        avpu_text: "P",
                        blood_pressure_diastolic: 80,
                        blood_pressure_systolic: 120,
                        body_temperature: 40,
                        clinical_risk: "Medium",
                        concentration: false,
                        cpap_peep: false,
                        create_date: "2014-12-01 14:15:13",
                        create_uid: [1, "Administrator"],
                        date_started: "2014-12-01 17:16:42",
                        date_terminated: "2014-12-01 17:16:53",
                        device_id: false,
                        display_name: "False",
                        flow_rate: false,
                        frequency: 240,
                        id: 83,
                        indirect_oxymetry_spo2: 90,
                        is_partial: false,
                        mews_score: 0,
                        name: false,
                        niv_backup: false,
                        niv_epap: false,
                        niv_ipap: false,
                        none_values: "['respiration_rate']",
                        null_values: "['niv_epap', 'concentration', 'flow_rate', 'cpap_peep', 'niv_ipap', 'niv_backup']",
                        order_by: false,
                        oxygen_administration_flag: false,
                        partial_reason: false,
                        patient_id: [11, "Littel, Alfreda"],
                        pulse_rate: 80,
                        respiration_rate: 28,
                        score: 5,
                        state: "completed",
                        terminate_uid: [19, "Nadine Bullock"],
                        three_in_one: true,
                        write_date: "2014-12-01 17:16:53",
                        write_uid: [1, "Administrator"]
                },
                {
                        __last_update: "2014-12-01 16:16:53",
                        activity_id: [700, "NEWS Observation"],
                        avpu_text: "V",
                        blood_pressure_diastolic: 80,
                        blood_pressure_systolic: 120,
                        body_temperature: 40,
                        clinical_risk: "Medium",
                        concentration: false,
                        cpap_peep: false,
                        create_date: "2014-12-01 13:15:13",
                        create_uid: [1, "Administrator"],
                        date_started: "2014-12-01 16:16:42",
                        date_terminated: "2014-12-01 16:16:53",
                        device_id: false,
                        display_name: "False",
                        flow_rate: false,
                        frequency: 240,
                        id: 83,
                        indirect_oxymetry_spo2: 90,
                        is_partial: false,
                        mews_score: 0,
                        name: false,
                        niv_backup: false,
                        niv_epap: false,
                        niv_ipap: false,
                        none_values: "[]",
                        null_values: "['niv_epap', 'concentration', 'flow_rate', 'cpap_peep', 'niv_ipap', 'niv_backup']",
                        order_by: false,
                        oxygen_administration_flag: false,
                        partial_reason: false,
                        patient_id: [11, "Littel, Alfreda"],
                        pulse_rate: 80,
                        respiration_rate: 18,
                        score: 5,
                        state: "completed",
                        terminate_uid: [19, "Nadine Bullock"],
                        three_in_one: true,
                        write_date: "2014-12-01 16:16:53",
                        write_uid: [1, "Administrator"]
                }
        ]

};