from . import test_acute_ed_count
from . import test_awol_count
from . import test_bed_count
from . import test_capacity_count
from . import test_extended_leave_count
from . import test_obs_stop_count
from . import test_on_ward_count
from . import test_ward_dashboard
from . import test_workload_count
